---
title: "Note_Introduction_H24071126葉嘉浤"
author: "H24071126葉嘉浤"
date: "2020/5/6"
output: html_document
---

# 1.介紹
## 計算
```{r}
#加減乘除
5 + 3
5 - 3
5 * 3
5 / 3
#次方
5 ^ 3
#相除後取餘數
5 %% 3
#相除後取商
5 %/% 3
```

## 序列
```{r}
1:10
#將序列取間隔
seq(1, 10, 2)
#指定多少個數形成序列
seq(1, 10, length.out = 6)
```

## 基本性質
```{r}
#指定一個名稱儲存計算值
a <- 3 ^ 5
b = 3 ^ 5
a
b
```

## 用設定好的名稱進行運算
```{r}
a <- 1000
b <- 4
a * b - a
```

## 特殊值
```{r}
NA
NaN #ex: 0/0
Inf #ex: 2/0
-Inf #ex: -2/0
pi
1e-3
```

### 命名物件
```{}
#須避免用下列字元命名:
#break; else; FALSE; F; TRUE; F; for; function; if; Inf; NA; NaN; next;repeat; return; while;

#用“.”或"_"命名一個有意義的物件
#score1, score2 
#score.John, score.Jack
```

## 更多運算功能
```{r}
#絕對值
abs(-2)
#指數、對數
exp(10); log(2); log2(2); log(10); log10(10);
```

##f其他function
```{r}
#“ˆ”或"**"代表多少次方
#sqrt => 將數字開根號
2 ** 3; 2^3;2^0.5; sqrt(2);
```

## 近似值
```{r}
round(125.78253)
#digit => 小數點後有幾位數，並對下一位數做四捨五入
round(125.78253, digits = 3)
round(125.78253, digits = -2);
round(83524587, digits = -3); round(83524587, digits = -5);
signif(125.78253, digits = 2);
#四捨五入
signif(83524587, digits = 3); signif(83524587, digits = 5);
#小數點後無條件捨去
floor(125.78253);
#小數點後無條件進位
ceiling(125.78253);
#取整數部分
trunc(125.78253); 
```

## 統計量
```{r}
x <- 1:25
mean(x)
var(x)
median(x)
quantile(x, c(0.1, 0.5, 0.7))
x <- c(1:25, NA)
summary(x)
```

## R is case-sensitive
```{r}

#如果打MEAN
x <- c(1:25)
#MEAN(x)
## Error in MEAN(x): could not find function "MEAN"

#使MEAN=mean
MEAN <- mean
MEAN(x)
```

## 物件
```{r}
#查看有哪些物件
objects()
ls()
#rm()可移除已立的物件
rm(x,y)
#再看一次已使用的物件
objects()
#可以在介面的右上角看到已使用的物件
```

# 2.向量
## 向量
```{r}
vt1 <- c(2:4)
vt2 <- c(3:6)
vt2 <- c(vt2, vt1)
vt2
vt2 <- c(vt2, vt1)
vt2
```

## 常用的function
```{r}
#向量長度
length(vt1) 
length(vt2)
#用[]選擇元素在向量中的位置來取出元素
#每個元素的索引與python和C不同
vt1[3]
vt2[c(3,5,7)]
#m元素也能用下列方式提取
vt1
vt1[-2]
vt2[-c(3:6)]
```

## 向量運算
```{r}
x <- c(3, 6, 9)
x * 3
x - 3
x ^ 3
y1 <- c(3, 2); y2 <- c(3, 2, 4);
#長度較長的向量，不是長度較短的向量的倍數
x^y1
x^y2
#兩個長度不同的向量做運算時，長度較短的向量會被重複使用，直到兩個向量長度一樣
c(1, 1, 2, 2, 3, 3, 4, 4, 5, 5,
6, 6, 7, 7, 8, 8, 9, 9, 10, 10) %% 2:3
#用rep()來延伸向量的長度
c(1, 1, 2, 2, 3, 3, 4, 4, 5, 5,
6, 6, 7, 7, 8, 8, 9, 9, 10, 10) %% rep(2:3, 10)
```

### 用相同的序列形成向量
```{r}
#用seq()和rep()產生相同的序列，形成向量
rep(3, 12)
rep(seq(2, 10, 2), 2)
rep(c(1, 4), c(3, 2))
rep(seq(2, 10, 2), rep(3, 5))
```

## 指派數值到向量
```{r}
Xvector <- rep(NA, 6)
Xvector[3] <- 12
Xvector[c(4:6)] <- rep(1, 3)
Xvector
#刪除NA
Xvector[-(1:2)]
## [1] 12 1 1 1
Xvector <- Xvector[-(1:2)]
Xvector
```

# 矩陣
#以列的方式建立矩陣
```{r}
#以列的方式建立矩陣
a <- 1:5; b <- 6:10;
c <- 11:15; d <- 16:20;
M1 <- rbind(a, b, c, d)
M1
#以行的方式建立矩陣
M2 <- cbind(a, b, c, d)
M2
```

## 由很多元素的向量建立矩陣
```{r}
X <- 1:20
matrix(X, nrow = 4, ncol = 5)
matrix(X, nrow = 5, ncol = 4)
matrix(X, nrow = 4, ncol = 5, byrow = TRUE)
matrix(X, nrow = 5, ncol = 4, byrow = TRUE)
```

## 矩陣特性
```{r}
dim(M1) #顯示矩陣的維度(M列N行)
colnames(M1); 
rownames(M1);
colnames(M1) <- c("V1","V2","V3","V4","V5")#將矩陣內每個行命名
```

## 取出矩陣內元素
```{r}
#用[]取出矩陣內的元素
M1[2, 4];
#M1[5, 5]; #Out of bond
M1[c(2, 4), 3]; 
M1[c(2, 4), c(3, 5)];
M1
```

## 取出矩陣的一行或一列
```{r}
M1[, 4]; 
#M1[5, ]; #超出範圍
M1[c(2, 4), ];
M1[, c(3, 5)]
```

## 取出矩陣內的元素
```{r}
M2
M2[5]
M2[13]
```